sonar.projectKey=pokemon-project
<<<<<<< Updated upstream
sonar.projectName=pokemon-project
sonar.organization=jorgexxvp
# Rutas de tus archivos fuente y pruebas
sonar.sources=apps

=======
sonar.organization=jorgexxvp
# Rutas de tus archivos fuente y pruebas
sonar.sources=src
sonar.tests=src/__tests__
>>>>>>> Stashed changes
